### ISSUE TITLE
GITHUB_URL does not work for BitBucket :upside_down_face:

### ISSUE THREAD

**Issue by yaakov-h** [justinbarrick/fluxcloud#15]
Well, duh, but there's one simple difference:

GitHub has `/commit/<sha>`
BitBucket has `/commits/<sha>`.

There's only a single-character between the two URL schemes.

Could URL support please be extended to include BitBucket as well?

**Comment by puzza007** [comment]
To do it in a backwards compatible way perhaps a new config item in addition to `github_url` that includes `/commit/` or `/commits/` in the `vcsLink`?

https://github.com/justinbarrick/fluxcloud/blob/master/pkg/formatters/default.go#L157

**Comment by justinbarrick** [comment]
Good catch! You can now set a COMMIT_TEMPLATE: https://github.com/justinbarrick/fluxcloud/#formatting-commit-links

**Comment by yaakov-h** [comment]
Thanks a bunch!
