### ISSUE TITLE
3031 taken

### ISSUE THREAD

**Issue by montyz** [justinbarrick/fluxcloud#16]
The new default install of flux recommends this line:

```
        # serve /metrics endpoint at different port.
        # make sure to set prometheus' annotation to scrape the port value.
        - --listen-metrics=:3031
```

In order to get fluxcloud to start I needed to change their prometheus port, since I didn't see any way to specify a different port in the fluxcloud env vars.

Not sure what the best answer is here, at least mentioning it in the deployment file would be helpful. If you could change to an unused port that would be great.

**Comment by justinbarrick** [comment]
Thanks for the report! I’ll look into changing the port today.
