### ISSUE TITLE
report errors?

### ISSUE THREAD

**Issue by montyz** [justinbarrick/fluxcloud#17]
I love seeing things get deployed, etc. on the slack channel. Would be great if I could get error messages from the flux logs as well, to know when I've committed something wrong.

**Comment by justinbarrick** [comment]
fluxcloud should be reporting any errors that flux reports to it. It’s not going to pick up everything from the flux log, but it will pick up manifest errors. If you’re not getting those are you on the latest version?

**Comment by montyz** [comment]
Yeah I do see manifest errors coming through. I don't remember the specific error for this, I had just assumed no errors were coming through at all.
