### ISSUE TITLE
Issue with CRDs

### ISSUE THREAD

**Issue by nicolerenee** [justinbarrick/fluxcloud#2]
I deployed bitnami's sealed secrets (https://github.com/bitnami-labs/sealed-secrets) into my cluster and now I get the following error in fluxcloud.

```
Request for:/v6/events
parsing default:customresourcedefinition/sealedsecrets.bitnami.com: invalid service ID
Request for:/v6/events
parsing default:customresourcedefinition/sealedsecrets.bitnami.com: invalid service ID
Request for:/v6/events
parsing default:customresourcedefinition/sealedsecrets.bitnami.com: invalid service ID
Request for:/v6/events
parsing default:customresourcedefinition/sealedsecrets.bitnami.com: invalid service ID
```

**Comment by justinbarrick** [comment]
This should be fixed in the latest version of fluxcloud (master-89f5fec). What version are you running?

**Comment by nicolerenee** [comment]
You are correct it is fixed on the latest version. I was running `master-a6c7844` since I grabbed it out of the example. Didn't even think to check the version. Thanks for the amazing tool!!

**Comment by justinbarrick** [comment]
Thanks! I've updated the examples now, too.
