### ISSUE TITLE
Only for Public github?

### ISSUE THREAD

**Issue by i5okie** [justinbarrick/fluxcloud#37]
Hi.
I've deployed both deployment and sidecar.. tried both.
It does not work. I've created a webhook and I see nothing in slack.
don't see any errors from fluxcloud or anything.

just nothing is happening.
tried this on two different clusters.

EKS cluster.
Kubernetes 1.13

flux is working.

**Comment by justinbarrick** [comment]
Did you configure `—connect` on Flux?

https://github.com/justinbarrick/fluxcloud#Setup

**Comment by i5okie** [comment]
of course!
..not

:) thank you!

works now.

**Comment by justinbarrick** [comment]
Great!
