### ISSUE TITLE
Append custom text to title

### ISSUE THREAD

**Issue by yarinm** [justinbarrick/fluxcloud#46]
I'm using MicrosoftTeams and unless I create a different connector with different names for each of my clusters, I have no way to identify which cluster produced the message.

My suggestion is add the ability to append custom prefix to the title for such use cases. WDYT?

**Comment by justinbarrick** [comment]
So, we haven’t documented it well, but it’s actually fully customizable. Check out this PR description: https://github.com/justinbarrick/fluxcloud/pull/12

**Comment by danslinky** [comment]
Question, how can I include an Environment Variable inside a template? I'm not very Go, but something like Hugo `getenv` or gomplate `.Env.FOO`
