### ISSUE TITLE
Can we have a new release? 

### ISSUE THREAD

**Issue by nabadger** [justinbarrick/fluxcloud#50]
Thanks for fluxcloud!

Is it possible to have a new tagged release - looks like the multiple-exporter option is not available in a release (and it's a really cool feature!).

Thanks again.

**Comment by justinbarrick** [comment]
Hey, thanks for the reminder! I’ll do this today.

**Comment by justinbarrick** [comment]
v0.3.9 is released!

**Comment by nabadger** [comment]
Thanks! :)
