### ISSUE TITLE
Implement 'failure' notifications

### ISSUE THREAD

**Issue by spolspol** [justinbarrick/fluxcloud#52]
It is great to be able to track flux events as they happen, however the really useful side of notifications are those that bring ones attention to when things don't go according to plan.

Positive notifications create a lot of chatter and are quickly being ignored by developer teams.
In most real-life scenarios it is typical to only enable notifications for when exceptions, such as failed deployments, happen.

**Comment by justinbarrick** [comment]
You can filter for the events you care about already using a template. See this PR for details: https://github.com/justinbarrick/fluxcloud/pull/12
